// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1787418800);
user_pref("app.update.lastUpdateTime.background-update-timer", 1787418800);
user_pref("app.update.lastUpdateTime.glean-addons-daily", 1787418800);
user_pref("app.update.lastUpdateTime.region-update-timer", 1787418800);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1787418800);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1787418800);
user_pref("browser.migration.version", 175);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1787418772);
user_pref("browser.search.region", "SG");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[],\"currentVersion\":24,\"newElementCount\":0}");
user_pref("distribution.iniFile.exists.appversion", "153.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.cache.lastUpdate", 1787418801);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260715202819");
user_pref("extensions.lastAppVersion", "153.0");
user_pref("extensions.lastPlatformVersion", "153.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.quarantinedDomains.list", "autoatendimento.bb.com.br,ibpf.sicredi.com.br,ibpj.sicredi.com.br,internetbanking.caixa.gov.br,www.ib12.bradesco.com.br,www2.bancobrasil.com.br");
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{6e43c946-fbb5-4c42-9b6a-b148eeca4486}\",\"addons\":{\"ipp-activator@mozilla.com\":{\"version\":\"0.2.20260622.182020\"}}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3b3db4fa-4cc5-46f0-9778-3529673a388d\",\"ipp-activator@mozilla.com\":\"59526d84-aaef-4795-8a19-35eb564b18dc\",\"pictureinpicture@mozilla.org\":\"324f4c1d-ea80-4a04-8149-d31456aa0427\",\"addons-search-detection@mozilla.com\":\"306fc383-3686-44df-99e5-ac1ea1a816ec\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"79583f8a-1995-4819-99db-a27e64721eb9\",\"default-theme@mozilla.org\":\"a1a5f80e-7bb3-47c2-ae6f-f1a643237eaa\"}");
user_pref("media.gmp-gmpopenh264.abi", "aarch64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "d69514fa5a04483674b9d5a9c2ab0c1736db6363f1afc83bad4e54f0c155949e34cdf9746e07f9d855b3fcad16da8b9e8d79b2707fa1ae1e9aaeaaab620d1026");
user_pref("media.gmp-gmpopenh264.lastDownload", 1787418806);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1787418805);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1787418806);
user_pref("media.gmp-gmpopenh264.version", "2.6.0");
user_pref("media.gmp-widevinecdm.abi", "aarch64-gcc3");
user_pref("media.gmp-widevinecdm.hashValue", "5ade9a40703c835026d26dc660cf5793a03e275229438f7ff7154116a33ce595d1ee99a79f6f0579231bdc9f51e72363d35c958f02ace911a7c47fb260402560");
user_pref("media.gmp-widevinecdm.lastDownload", 1787418809);
user_pref("media.gmp-widevinecdm.lastInstallStart", 1787418804);
user_pref("media.gmp-widevinecdm.lastUpdate", 1787418810);
user_pref("media.gmp-widevinecdm.version", "4.10.3050.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "7c4115da-f617-4eff-8b80-e6dde20ee95e");
user_pref("pdfjs.enabledCache.state", true);
user_pref("services.settings.clock_skew_seconds", -39);
user_pref("services.settings.last_etag", "1787410627648");
user_pref("services.settings.last_update_seconds", 1787418839);
user_pref("services.settings.main.addons-manager-settings.last_check", 1787418839);
user_pref("services.settings.main.ai-window-prompts.last_check", 1787418839);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1787418839);
user_pref("services.settings.main.cfr.last_check", 1787418839);
user_pref("services.settings.main.cookie-banner-rules-list.last_check", 1787418839);
user_pref("services.settings.main.devtools-compatibility-browsers.last_check", 1787418839);
user_pref("services.settings.main.devtools-devices.last_check", 1787418839);
user_pref("services.settings.main.doh-config.last_check", 1787418839);
user_pref("services.settings.main.doh-providers.last_check", 1787418839);
user_pref("services.settings.main.fingerprinting-protection-overrides.last_check", 1787418839);
user_pref("services.settings.main.hijack-blocklists.last_check", 1787418839);
user_pref("services.settings.main.language-dictionaries.last_check", 1787418839);
user_pref("services.settings.main.message-groups.last_check", 1787418839);
user_pref("services.settings.main.moz-essential-domain-fallbacks.last_check", 1787418839);
user_pref("services.settings.main.ms-language-packs.last_check", 1787418839);
user_pref("services.settings.main.newtab-wallpapers-v2.last_check", 1787418839);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1787418839);
user_pref("services.settings.main.nimbus-secure-experiments.last_check", 1787418839);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1787418839);
user_pref("services.settings.main.partitioning-exempt-urls.last_check", 1787418839);
user_pref("services.settings.main.password-recipes.last_check", 1787418839);
user_pref("services.settings.main.password-rules.last_check", 1787418839);
user_pref("services.settings.main.query-stripping.last_check", 1787418839);
user_pref("services.settings.main.remote-permissions.last_check", 1787418839);
user_pref("services.settings.main.search-categorization.last_check", 1787418839);
user_pref("services.settings.main.search-config-icons.last_check", 1787418839);
user_pref("services.settings.main.search-config-overrides-v2.last_check", 1787418839);
user_pref("services.settings.main.search-config-v2.last_check", 1787418839);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1787418839);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1787418839);
user_pref("services.settings.main.sites-classification.last_check", 1787418839);
user_pref("services.settings.main.third-party-cookie-blocking-exempt-urls.last_check", 1787418839);
user_pref("services.settings.main.top-sites.last_check", 1787418839);
user_pref("services.settings.main.tracking-protection-lists.last_check", 1787418839);
user_pref("services.settings.main.translations-models-v2.last_check", 1787418839);
user_pref("services.settings.main.translations-models.last_check", 1787418839);
user_pref("services.settings.main.translations-wasm.last_check", 1787418839);
user_pref("services.settings.main.url-classifier-exceptions.last_check", 1787418839);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1787418839);
user_pref("services.settings.main.url-parser-default-unknown-schemes-interventions.last_check", 1787418839);
user_pref("services.settings.main.urlbar-persisted-search-terms.last_check", 1787418839);
user_pref("services.settings.main.websites-with-shared-credential-backends.last_check", 1787418839);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.telemetry.previousBuildID", "20260715202819");
